### ISSUE TITLE
Add Tests for Discordian Calendar's Day of the Week Feature

### ISSUE THREAD

**Issue by carlosfrodrigues** [carlosfrodrigues/discordian-calendar#1]
The last feature added to the Discordian calendar was a function to know what day of the week corresponds to a specific date. 
We need to ensure that the `Discordian.Calendar.day_of_week/4` function is working correctly and consistently. 

The purpose of this issue is to create tests that verify the accuracy of the day of the week calculation based on a given Discordian date.

**Comment by giovannism20** [comment]
Is that function, right @carlosfrodrigues ?
https://github.com/carlosfrodrigues/discordian-calendar/blob/main/lib/discordian/calendar.ex#L69-L78

**Comment by carlosfrodrigues** [comment]
Yes, this one

**Comment by giovannism20** [comment]
Sure, I'll try to make it!

**Comment by giovannism20** [comment]
I've noticed that doesn't have a test file specific for calendar.ex, should I create it?

**Comment by carlosfrodrigues** [comment]
> I've noticed that doesn't have a test file specific for calendar.ex, should I create it?

Sure, that would be great
